[workspace]
members = [
    "bi_result",
    "cargo_pkg_info",
    "growable_iter",
    "infinite_iterators",
    "map_range",
    "nonempty_vec",
    "some_macros",
    "span",
    "type_list",
    "vec_like",
]